#!/bin/bash
# Setup script for aesc - auto-generates .env with your user ID
set -e

echo "Setting up aesc..."

# Detect user and group IDs
DETECTED_UID=$(id -u)
DETECTED_GID=$(id -g)

# Create or update .env file
cat > .env << EOF
# Auto-generated by setup.sh
# docker-compose automatically loads this file

# Your user/group IDs (detected automatically)
UID=$DETECTED_UID
GID=$DETECTED_GID

# LLM Configuration - ADD YOUR API KEY HERE
# Uncomment and set your API key:
# ANTHROPIC_API_KEY=sk-ant-your-key-here
# AESC_MODEL_NAME=claude-sonnet-4-5-20250929

# Or use OpenAI:
# OPENAI_API_KEY=sk-your-key-here
# AESC_MODEL_NAME=gpt-4

# Or use local Ollama (free):
# OLLAMA_BASE_URL=http://host.docker.internal:11434/v1
# AESC_MODEL_NAME=llama3
EOF

echo "✅ Created .env with UID=$DETECTED_UID and GID=$DETECTED_GID"
echo ""
echo "Next steps:"
echo "1. Edit .env and add your API key"
echo "2. Run: docker-compose run --rm aesc"
echo ""
echo "That's it! No exports needed, docker-compose reads .env automatically."
